export const mockArticles = [
  {
    id: "1",
    title: "Core Banking Network Topology",
    version: "v3.2",
    badge: "",
    excerpt:
      "VLAN segmentation, firewall zones, and redundant link configuration for production banking networks.",
    content:
      "This document outlines the core banking network topology.\n\n## VLAN Segmentation\nWe use VLANs 100-199 for core services...\n\n## Firewall Zones\nStrict isolation between DMZ, App, and DB tiers.\n\n## Failover Procedures\nEnsure BGP convergence times are below 50ms.",
    category: "Network",
    categoryColor: "bg-blue-100 text-blue-800",
    categoryIcon: "Server",
    author: "JD",
    status: "Published",
    date: "2d ago",
    views: 148,
  },
  {
    id: "2",
    title: "Incident Response Runbook — P1/P2",
    version: "",
    badge: "Critical",
    excerpt:
      "Step-by-step escalation matrix, war room setup, comms templates, and regulatory notification timelines.",
    content:
      "When a P1/P2 incident occurs:\n1. Open War Room\n2. Notify Stakeholders\n3. Engage L3 Support\n4. Regulatory notification within 2 hours.",
    category: "Security",
    categoryColor: "bg-amber-100 text-amber-800",
    categoryIcon: "ShieldAlert",
    author: "MR",
    status: "Published",
    date: "5d ago",
    views: 312,
  },
  {
    id: "3",
    title: "DR Failover SOP — Core Banking System",
    version: "v2.0",
    badge: "",
    excerpt:
      "RTO/RPO targets, failover triggers, validation checklist, and BSP notification requirements.",
    content:
      "Disaster Recovery standard operating procedure.\n\nRTO: 4 hours\nRPO: 15 minutes\n\nFailover triggers include full DC outage or core DB corruption.",
    category: "DR/BCP",
    categoryColor: "bg-green-100 text-green-800",
    categoryIcon: "Activity",
    author: "RS",
    status: "Pending",
    date: "1w ago",
    views: 96,
  },
  {
    id: "4",
    title: "API Gateway — Auth & Rate Limiting Policy",
    version: "v1.4",
    badge: "",
    excerpt:
      "OAuth 2.0 flow, token expiry settings, rate limit tiers, and PCI DSS compliance mapping.",
    content:
      "API Gateway policies:\n- Rate limit: 1000 req/min for internal, 100 req/min for external.\n- Auth: OAuth 2.0 with JWT.",
    category: "Engineering",
    categoryColor: "bg-indigo-100 text-indigo-800",
    categoryIcon: "Blocks",
    author: "JD",
    status: "Draft",
    date: "2w ago",
    views: 74,
  },
  {
    id: "5",
    title: "Multi-Region Azure Deployment Guide",
    version: "v1.1",
    badge: "",
    excerpt:
      "Best practices for deploying cloud resources across secondary regions using Terraform.",
    content:
      "Cloud deployment strategies...\n\nAvoid single points of failure by routing traffic across Availability Zones.",
    category: "Cloud & Hybrid",
    categoryColor: "bg-cyan-100 text-cyan-800",
    categoryIcon: "Cloud",
    author: "AT",
    status: "Published",
    date: "3w ago",
    views: 210,
  },
  {
    id: "6",
    title: "PostgreSQL HA Cluster Configuration",
    version: "v4.0",
    badge: "Update",
    excerpt:
      "Patroni and etcd configuration for highly available PostgreSQL 15 database clusters.",
    content:
      "Database high availability guidelines for 2026. Use streaming replication and automatic failover.",
    category: "Databases",
    categoryColor: "bg-orange-100 text-orange-800",
    categoryIcon: "Database",
    author: "MK",
    status: "Published",
    date: "1m ago",
    views: 45,
  },
  {
    id: "7",
    title: "GitLab CI/CD Golden Pipelines",
    version: "v2.1",
    badge: "",
    excerpt:
      "Standardized pipeline templates for automated scanning, testing, and container deployment.",
    content:
      "Every project must inherit these gold standard CI pipelines to satisfy DevSecOps requirements.",
    category: "CI/CD & DevOps",
    categoryColor: "bg-purple-100 text-purple-800",
    categoryIcon: "GitBranch",
    author: "JD",
    status: "Published",
    date: "2h ago",
    views: 19,
  },
  {
    id: "8",
    title: "Enterprise Microservices API Catalog",
    version: "",
    badge: "Draft",
    excerpt: "Directory of all active internal REST and gRPC endpoints.",
    content:
      "API documentation directory.\n\n- Payment Service\n- Identity Service\n- Transaction Ledger",
    category: "API Catalog",
    categoryColor: "bg-teal-100 text-teal-800",
    categoryIcon: "Blocks",
    author: "SV",
    status: "Pending",
    date: "4d ago",
    views: 33,
  },
  {
    id: "9",
    title: "Emergency Change Advisory Board (eCAB)",
    version: "v1.0",
    badge: "",
    excerpt:
      "Expedited process for implementing emergency fixes outside the standard release window.",
    content:
      "eCAB processes for P1 incident resolution. Only valid if system is critically degraded.",
    category: "Change Mgmt",
    categoryColor: "bg-yellow-100 text-yellow-800",
    categoryIcon: "ListChecks",
    author: "MR",
    status: "Published",
    date: "1y ago",
    views: 541,
  },
  {
    id: "10",
    title: "Information Security Policy 2026",
    version: "v5.0",
    badge: "Required",
    excerpt:
      "Annual mandatory reading for all IT staff. Covers data classification and acceptable use.",
    content:
      "Information governance rules for all employees dealing with sensitive and confidential data.",
    category: "Policies & SOPs",
    categoryColor: "bg-pink-100 text-pink-800",
    categoryIcon: "FileText",
    author: "Admin",
    status: "Published",
    date: "2d ago",
    views: 999,
  },
];

export const mockCategories = [
  {
    id: "cat-1",
    title: "Network & Infrastructure",
    filterCategory: "Network",
    icon: "Server",
    count: "84 articles · 12 pending",
    colorClass: "bg-blue-100 text-blue-700",
  },
  {
    id: "cat-2",
    title: "Security & Compliance",
    filterCategory: "Security",
    icon: "ShieldCheck",
    count: "71 articles · 3 pending",
    colorClass: "bg-green-100 text-green-700",
  },
  {
    id: "cat-3",
    title: "Engineering Standards",
    filterCategory: "Engineering",
    icon: "Code",
    count: "58 articles · 1 pending",
    colorClass: "bg-indigo-100 text-indigo-700",
  },
  {
    id: "cat-4",
    title: "DR & Business Continuity",
    filterCategory: "DR/BCP",
    icon: "Activity",
    count: "42 articles · 2 pending",
    colorClass: "bg-amber-100 text-amber-700",
  },
  {
    id: "cat-5",
    title: "API & Integration Catalog",
    filterCategory: "API Catalog",
    icon: "Blocks",
    count: "37 articles · 0 pending",
    colorClass: "bg-teal-100 text-teal-700",
  },
  {
    id: "cat-6",
    title: "SOPs & Policies",
    filterCategory: "Policies & SOPs",
    icon: "ListChecks",
    count: "20 articles · 0 pending",
    colorClass: "bg-rose-100 text-rose-700",
  },
];

export const mockActivities = [
  {
    id: "1",
    text: 'JD updated "Core Banking Network Topology"',
    time: "2 hours ago",
    color: "bg-blue-500",
  },
  {
    id: "2",
    text: 'RS approved "DR Failover SOP v2.0"',
    time: "Yesterday",
    color: "bg-green-500",
  },
  {
    id: "3",
    text: "PCI DSS article flagged for review",
    time: "3 days ago",
    color: "bg-amber-500",
  },
  {
    id: "4",
    text: "New P1 runbook published by MR",
    time: "5 days ago",
    color: "bg-red-500",
  },
  {
    id: "5",
    text: "ISO 27001 policy article reviewed",
    time: "1 week ago",
    color: "bg-slate-300",
  },
];

export const mockCompliance = [
  {
    id: "1",
    text: "BSP Circular 1140 — IT Risk Management",
    status: "Covered",
    color: "bg-green-100 text-green-800",
  },
  {
    id: "2",
    text: "ISO/IEC 27001 — Information Security",
    status: "Covered",
    color: "bg-green-100 text-green-800",
  },
  {
    id: "3",
    text: "PCI DSS v4.0 — Cardholder Data Environment",
    status: "Partial",
    color: "bg-amber-100 text-amber-800",
  },
  {
    id: "4",
    text: "BSP MORB — Operational Risk Controls",
    status: "Review Due",
    color: "bg-red-100 text-red-800",
  },
];

export const mockAuditLogs = [
  {
    id: "1",
    action: "Update",
    item: "Core Banking Network Topology",
    user: "jdoe",
    date: "2026-05-08 03:15 PM",
  },
  {
    id: "2",
    action: "Approve",
    item: "DR Failover SOP v2.0",
    user: "rsmith",
    date: "2026-05-07 10:42 AM",
  },
  {
    id: "3",
    action: "Flag",
    item: "PCI DSS Policy",
    user: "mreyes",
    date: "2026-05-05 09:20 AM",
  },
  {
    id: "4",
    action: "Publish",
    item: "Incident Response Runbook",
    user: "jdoe",
    date: "2026-05-03 04:55 PM",
  },
  {
    id: "5",
    action: "Create",
    item: "API Gateway Policy",
    user: "jdoe",
    date: "2026-04-20 11:10 AM",
  },
];
